language: python
python: 2.6 2.7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenmpi-dev openmpi-bin libsundials-serial-dev libsundials-serial python-pip git

install:
  - python setup.py install



script:
  - echo "INSTALLATION DONE"
