sudo: required
services:
  - docker
language: python
python: 2.7

install:
- docker pull labestiol/signetsim-precise

script:
- docker run -v $(pwd):/root labestiol/signetsim-precise /bin/sh -c "cd /root/; python setup.py install; python fix_libsedml_addChild.py; python -m unittest libsignetsim.tests.sbmltestsuite.TestSuite_l3v1"

after_script:
- coveralls