sudo: required
services:
  - docker
language: python
python: 2.7

before_install:
- docker pull labestiol/signetsim-precise

install:
- docker run -di --name test_env -v $(pwd):/root/ labestiol/signetsim-precise /bin/sh -c "cd /root/; bash scripts/install.sh"

script:
- docker exec test_env /bin/sh -c "cd root; bash scripts/run_tests.sh sbml-test-suite l1v2"

after_script:
- docker exec test_env /bin/sh -c "cd root; coveralls"
