sudo: required
services:
  - docker
language: python
python: 2.7

before_install:
- docker pull labestiol/signetsim-env

script:
- docker run labestiol/signetsim-env /bin/sh -c "cd /root/; coverage run -m unittest test"

after_script:
- coveralls