language: python
python: 2.7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenmpi-dev openmpi-bin libsundials-serial-dev libsundials-serial liblapack-dev libblas-dev libatlas-dev libfreetype6-dev libpng12-dev python-pip git

install:
  - python setup.py install


script:
  - python -m unittest discover libsignetsim -v
