sudo: required
services:
  - docker
language: python
python: 2.7

before_install:
- pip install coveralls
- docker pull labestiol/signetsim-precise

install:
- docker run -di --name test_env -v $(pwd):/root/libSigNetSim labestiol/signetsim-precise bash
- docker exec test_env /bin/bash -c "cd /root/libSigNetSim; bash scripts/install.sh"

script:
- docker exec test_env /bin/bash -c "cd root/libSigNetSim; bash scripts/run_tests.sh others"

after_script:
- ls -al
- coveralls