sudo: required

services: docker

language: python

python: 2.7

env:
  - TEST_SUITE=sbml-test-suite VERSION=3.1
  - TEST_SUITE=sbml-test-suite VERSION=2.5
  - TEST_SUITE=sbml-test-suite VERSION=2.4
  - TEST_SUITE=sbml-test-suite VERSION=2.3
  - TEST_SUITE=sbml-test-suite VERSION=2.2
  - TEST_SUITE=sbml-test-suite VERSION=2.1
  - TEST_SUITE=sbml-test-suite VERSION=1.2
  - TEST_SUITE=others

before_install:
- pip install coveralls
- docker pull signetsim/travis_testenv:stretch

install:
- docker run -di --name test_env -v $(pwd):/home/travis/build/vincent-noel/libSigNetSim signetsim/travis_testenv:stretch bash
- docker exec test_env chown -R www-data:www-data /home/travis/build/vincent-noel/libSigNetSim
- docker exec test_env /bin/bash -c "cd /home/travis/build/vincent-noel/libSigNetSim; bash scripts/install_dep.sh"
- docker exec test_env /bin/bash -c "cd /home/travis/build/vincent-noel/libSigNetSim; scripts/install.sh"

script:
- docker exec -u www-data test_env /bin/bash -c "cd /home/travis/build/vincent-noel/libSigNetSim; bash scripts/run_tests.sh $TEST_SUITE $VERSION"

after_script:
- coveralls