sudo: required
services:
  - docker
language: python
python: 2.7

before_install:
- docker pull labestiol/signetsim-precise

install:
- docker run -d -v $(pwd):/root labestiol/signetsim-precise /bin/sh -c "cd /root/; python setup.py install"
- docker run -d -v $(pwd):/root labestiol/signetsim-precise /bin/sh -c "cd /root/; python fix_libsedml_addChild.py"

script:
- docker run -v $(pwd):/root labestiol/signetsim-precise /bin/sh -c "cd /root/; coverage run -m unittest test"

after_script:
- coveralls