language: python
python: 2.7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenmpi-dev openmpi-bin libsundials-serial-dev libsundials-serial liblapack-dev libblas-dev libatlas-dev libfreetype6-dev libpng12-dev libatlas-base-dev python-dev python-pip python-setuptools git subversion gfortran g++ gcc make pkg-config unzip wget

install:
  - python setup.py install


script:
  - python -m unittest libsignetsim.sedml.tests.TestSedmlCompatibility
  - python -m unittest libsignetsim.simulation.tests.TestTimeseries
  - python -m unittest libsignetsim.simulation.tests.TestSteadyStates
  - python -m unittest libsignetsim.simulation.tests.TestSbmlCompatibility
  - python -m unittest libsignetsim.simulation.tests.TestBiomodelsCompatibility
  - python -m unittest libsignetsim.optimization.tests.TestOptimization


