#docker-compose.yml
version: '3.3'
services:
  libsignetsim-notebook:
    build:
      context: ./
      dockerfile: ./scripts/docker/Dockerfile
    image: signetsim/notebook:develop

  libsignetsim-notebook-python3:
    build:
      context: ./
      dockerfile: ./scripts/docker-python3/Dockerfile
    image: signetsim/notebook:develop-python3