#docker-compose.yml
version: '3.3'
services:
  notebook-py2:
    build:
      context: ./
      dockerfile: ./scripts/docker-py2/Dockerfile
    image: signetsim/notebook:master-py2
    container_name: libsignetsim-notebook-py2
    ports:
      - "8888:8888"

  notebook:
    build:
      context: ./
      dockerfile: ./scripts/docker-py3/Dockerfile
    image: signetsim/notebook:master
    container_name: libsignetsim-notebook
    ports:
      - "8888:8888"
